var message_data=[
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	},
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	},
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	},
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	},
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	},
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	},
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	},
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	},
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	},
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	},
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	},
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	},
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	},
	{
		'type':'会诊消息',
		'time':'09-30 18:01',
		'content':'您有一条新的会诊申请，请注意查看！',
		'status':'已读',
		'more':'查看详情'
	}
];

var patients_data=[
	{
		'name':'陈林坤',
		'hospital':'东',
		'type':'住院',
		'sex':'男',
		'age':'82岁',
		'department':'肿瘤科',
		'description':''
	},
	{
		'name':'王春梅',
		'hospital':'西',
		'type':'门诊',
		'sex':'女',
		'age':'56岁',
		'department':'康复医学科',
		'description':'脊椎退行性病变'
	},
	{
		'name':'王梅',
		'hospital':'东',
		'type':'门诊',
		'sex':'女',
		'age':'76岁',
		'department':'康复医学科',
		'description':'脊椎退行性病变脊椎退行性病变'
	},
	{
		'name':'陈林坤',
		'hospital':'东',
		'type':'住院',
		'sex':'男',
		'age':'82岁',
		'department':'肿瘤科',
		'description':''
	},
	{
		'name':'陈林',
		'hospital':'西',
		'type':'住院',
		'sex':'男',
		'age':'82岁',
		'department':'康复医学科',
		'description':'脊椎退行性病变'
	},
	{
		'name':'王春梅',
		'hospital':'西',
		'type':'门诊',
		'sex':'女',
		'age':'56岁',
		'department':'康复医学科',
		'description':'脊椎退行性病变'
	},
	{
		'name':'王梅',
		'hospital':'东',
		'type':'门诊',
		'sex':'女',
		'age':'76岁',
		'department':'康复医学科',
		'description':'脊椎退行性病变脊椎退行性病变'
	},
	{
		'name':'王春梅',
		'hospital':'西',
		'type':'门诊',
		'sex':'女',
		'age':'56岁',
		'department':'康复医学科',
		'description':'脊椎退行性病变'
	},
	{
		'name':'陈林坤',
		'hospital':'东',
		'type':'住院',
		'sex':'男',
		'age':'82岁',
		'department':'肿瘤科',
		'description':''
	},
	{
		'name':'王春梅',
		'hospital':'西',
		'type':'门诊',
		'sex':'女',
		'age':'56岁',
		'department':'康复医学科',
		'description':'脊椎退行性病变'
	},
	{
		'name':'王梅',
		'hospital':'东',
		'type':'门诊',
		'sex':'女',
		'age':'76岁',
		'department':'康复医学科',
		'description':'脊椎退行性病变脊椎退行性病变'
	},
	{
		'name':'王梅',
		'hospital':'东',
		'type':'门诊',
		'sex':'女',
		'age':'76岁',
		'department':'康复医学科',
		'description':'脊椎退行性病变脊椎退行性病变'
	}
];